apps/main/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^home$', views.index, name='index'),
    url(r'^home/add$', views.add),
    url(r'^home/edit/([0-9]+)/$', views.edit),
    url(r'^home/delete/([0-9]+)$', views.delete),
    url(r'^home/edit/([0-9]+)/update$', views.update)
	]
	

pythonblackbelt/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^main/', include('apps.main.urls', namespace="main")),
	url(r'^login/',include('apps.login.urls', namespace="login")),
	url(r'^',include('apps.login.urls', namespace="login")),

]

apps/main/models.py
from __future__ import unicode_literals
from django.db import models
from ..login.models import User, UserManager
import datetime
class TaskManager(models.Manager):

    def todays_tasks(self, user_id):
        return self.filter(creator=user_id, date=datetime.date.today())
    def future_tasks(self, user_id):
        return self.filter(creator=user_id, date__gt=datetime.date.today()).order_by('title').distinct


def validate_future_date(value):
    if value < datetime.date.today():
        raise ValidationError(_('Today\'s date or some date in the future please!'))


class Task(models.Model):
    title = models.CharField(max_length=255)
    STATUS_CHOICES = (
        (1, 'Done'),
        (2, 'Pending'),
        (3, 'Missed'),
    )
    status = models.IntegerField(default = 2, choices=STATUS_CHOICES)
    date = models.DateField(auto_now_add=False, auto_now=False, validators=[validate_future_date])
    time = models.TimeField(auto_now=False, auto_now_add=False)
    creator =  models.ForeignKey(User, related_name="itemcreator", on_delete=models.CASCADE)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    taskMgr = TaskManager()
    objects = models.Manager()

    def is_done(self):
        return self.status == 1

apps/main/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib import messages
from django.urls import reverse

from .models import Task, TaskManager
from ..login.models import User, UserManager
import datetime

# Create your views here.
def index(request):
    try:
	cookie = request.session['user_id']
        user =  User.Usermgr.filter(id=request.session['user_id'])
        name = user[0].first_name
        todays_tasks = Task.taskMgr.todays_tasks(user[0].id)
        future_tasks = Task.taskMgr.future_tasks(user[0].id) 

        context = {
            'name': name,
            'todays_tasks': todays_tasks,
            'future_tasks': future_tasks,
            'date' : datetime.date.today()
        }
        return render(request, 'main/home.html', context)
    except KeyError:
        return redirect('/')


def add(request):
    now= datetime.datetime.now()
    user_list =  User.Usermgr.filter(id=request.session['user_id'])
    t_date = request.POST['date']
    t_time = request.POST['time']
    title = request.POST['title']
    t_date_time = ('%s %s' % (t_date, t_time))
    try: 
        t_date_time = datetime.datetime.strptime(t_date_time, '%Y-%m-%d %H:%M')
	print t_date_time
	print now
    except ValueError:
        messages.add_message(request, messages.ERROR, 'Please enter a date in the format YYYY-MM-DD')
        return redirect('../home')

    if len(t_date) < 1:
        messages.add_message(request, messages.ERROR, 'You must complete the Date Field!')
    elif len(t_date) < 1:
        messages.add_message(request, messages.ERROR, 'You must complete the Time Field!')
    elif datetime.datetime.now() > t_date_time:
        messages.add_message(request, messages.ERROR, 'Only current and future time is allowed! ')
    elif len(title) < 1:
        messages.add_message(request, messages.ERROR, 'You must complete the Task Field!')
    
    else:
        task = Task(title=title, date=t_date, time=t_time, creator=user_list[0])
        task.save()
    return redirect(('../home'))


def edit(request, task_id):
    try:
        cookie= request.session['user_id']
        task =  Task.objects.get(id=task_id)
        context = {'task' : task, 'date':task.date.strftime('%Y-%m-%d'), 'time':task.time.strftime('%I:%M %p')}
        return render(request, 'main/edit.html', context)
    except:
	return redirect('/')

def update(request, task_id):

    if request.method == "POST":
        user_list =  User.Usermgr.filter(id=request.session['user_id'])
        task_list =  Task.taskMgr.filter(id=request.POST['id'])
        task = task_list[0]
        context = {'task' : task, 'date':task.date.strftime('%Y-%m-%d')}
        t_date = request.POST['date']
        t_time = request.POST['time']
        title = request.POST['title']
        status = request.POST['status']
        t_date_time = ('%s %s' % (t_date, t_time))
	try:
	    t_date_time = datetime.datetime.strptime(t_date_time, '%Y-%m-%d %H:%M')
        except ValueError:
            messages.add_message(request, messages.ERROR, 'Please enter a date in the format YYYY-MM-DD')
            return redirect('../home')

        if len(t_date) < 1:
            messages.add_message(request, messages.ERROR, 'You must complete the Date Field!')
            return render(request, 'main/edit.html', context)
        elif len(t_time) < 1:
            messages.add_message(request, messages.ERROR, 'You must complete the Time Field!')
            return render(request, 'main/edit.html', context)
        elif datetime.datetime.now() > t_date_time:
            messages.add_message(request, messages.ERROR, 'Only current and future time is allowed! ')
            return render(request, 'main/edit.html', context)
        elif len(title) < 1:
            messages.add_message(request, messages.ERROR, 'You must complete the Task Field!')
            return render(request, 'main/edit.html', context)
        else:
            task_list.update(title=title, date=t_date, time=t_time, status=status, creator=user_list[0])
            #task.save()
            return redirect('../../../home')

def delete(request, task_id):
    task = Task.objects.get(id = task_id)
    task.delete()
    return redirect('../../home')

apps/main/templates/main/edit.html
<html>
  <head>
    <title>Edit Page</title>
    {% load staticfiles %}
  </head>
  <body>
        <div id="header">
        <form action='/index'>
            {% csrf_token %}
            <input type='submit' name='dashboard' value='Dashboard'/>
        </form>
        <form action='/logout'>
            {% csrf_token %}
            <input type='submit' name='logout' value='Logout'/>
        </form>
        </div>
        <div id="change_appointments">
            <form action="update" method='POST'>
                {% csrf_token %}
                <p>Task: <input type="text" name="title" value={{task.title}}></p>
                <p>Status:
                    <select name='status'>
                        <option value="1">Done</option>
                        <option value="2">Pending</option>
                        <option value="3">Missed</option>
                    </select>
                </p>
                <p>Date(YYYY-MM-DD): <input type="date" name="date" value={{date}}></p>
                <p>Time: <input type="time" name="time" value={{time}}></p>
				<input type="hidden" name='id' value={{task.id}}>
                <input type='submit' name='update' value='Update'/>
            </form>
			{% if messages %}
                <ul class='messages'>
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
  </body>
</html>

apps/main/templates/main/home.html
<html>
  <head>
    <title>Login and Registration</title>
        {% load staticfiles %}
  </head>
  <body>
        <div id="header">
                <h3>Hello, {{ name }}!</h3>
        <form action="{% url 'login:logout' %}">
            {% csrf_token %}
            <input type='submit' name='logout' value='Logout'/>
        </form>
        </div>
        <div id="appointments">
            <p>Here are your appointments for today, {{date}}:<p>
            <table>
					<tr>
                        <th>Tasks</th>
                        <th>Time</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>

					{% for task in todays_tasks %}
                        <tr>
							<td>{{task.title}}</td>
							<td>{{task.time}}</td>
							<td>{{task.get_status_display}}</td>
							{% if not task.is_done %}
								<td><a href="home/edit/{{task.id}}">Edit</a> <a href="home/delete/{{task.id}}">Delete</a></td>
							{% endif %}
						</tr>
                    {% endfor %}

            </table>
            <p>Your other appointments:<p>
            <table>

                    <tr>
                        <th>Tasks</th>
                        <th>Date</th>
                        <th>Time</th>
                    </tr>

                    {% for task in future_tasks %}
                        <tr>
							<td>{{task.title}}</td>
							<td>{{task.date}}</td>
							<td>{{task.time}}</td>
						</tr>
                    {% endfor %}

            </table>
        </div>
        <div id="adding">
            <p>Add Appointment<p>
            <form action="home/add" method='POST'>
                {% csrf_token %}
                <p>Date: <input type="date" name="date"></p>
                <p>Time: <input type="time" name="time"></p>
                <p>Task: <input type="text" name="title"></p>
                <input type='submit' name='add' value='Add'/>
            </form>
			{% if messages %}
                <ul class='messages'>
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
  </body>
</html>