apps/login/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register$', views.register, name='register'),
    url(r'^login$', views.login, name='login'),
    url(r'^logout$', views.logout, name='logout'),
]

pythonblackbelt/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^main/', include('apps.main.urls', namespace="main")),
	url(r'^login/',include('apps.login.urls', namespace="login")),
	url(r'^',include('apps.login.urls', namespace="login")),

]

apps/login/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib import messages
import re, bcrypt, datetime
EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')

# Create your models here.
class UserManager(models.Manager):
    def register(self, f_name, l_name, email, passw, cpass, dob):
        print f_name, l_name, email, passw, cpass
        errors = []
	today = datetime.datetime.now()
        successes = []
	t_date_time = ('%s %s' % (dob, '12:00'))
	try:
            t_date_time = datetime.datetime.strptime(t_date_time, '%Y-%m-%d %H:%M')
            print t_date_time
        except ValueError:
            messages.add_message(request, messages.ERROR, 'Please enter a date in the format YYYY-MM-DD')
            return redirect('../home')

	if len(dob) < 1:
	    errors.append('please enter your DOB')
	    valid = False
	if t_date_time > today:
	    errors.append(' Enter a valid DOB')
        if len(email) < 1:
            errors.append("An email must be provided.")
            valid = False
        elif not EMAIL_REGEX.match(email):
            errors.append("Invalid email provided.")
            valid = False
        elif User.objects.filter(email=email).exists():
            errors.append("Email is already in use. Please log in or try another email.")
            valid = False

        if len(f_name) < 2:
            errors.append("First name must be atleast two characters long.")
            valid = False
        elif re.search(r'[0-9]', f_name):
            errors.append("First name cannot contain a number.")
            valid = False
        elif not f_name.isalpha():
            errors.append("First name can only have letters.")
            valid = False

        if len(l_name) < 2:
            errors.append("Last name must be atleast two characters long.")
            valid = False
        elif re.search(r'[0-9]', l_name):
            errors.append("Last name cannot contain a number.")
            valid = False
        elif not l_name.isalpha():
            errors.append("Last name can only have letters.")
            valid = False

        if len(passw) < 1:
            errors.append("Password cannot be empty.")
            valid = False
        elif len(passw) < 8:
            errors.append("Password must be longer than 8 characters.")
            valid = False

        if len(cpass) < 1:
            errors.append("Confirm password cannot be empty.")
            valid = False
        elif passw != cpass:
            errors.append("Passwords must match.")
            valid = False

        if valid:
            passw_enc = bcrypt.hashpw(passw.encode(), bcrypt.gensalt())
            data = {
                'first_name': f_name,
                'last_name': l_name,
                'email': email,
                'password': passw_enc
            }
            User.objects.create(**data)

            successes.append("Account successfully created. Please log in now.")

        return (valid, errors, successes)

    def login(self, email, passw):
        if not email or not passw:
            return (False, "Both email and password fields are required to login.")

        data = User.objects.get(email=email)
        hashed = data.password.encode()

        if bcrypt.hashpw(passw.encode(), hashed) == hashed:
            return (True, "Successful login!", data)
        else:
            return (False, "Incorrect password or email. Please try again.")


class User(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    email = models.EmailField()
    password = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    Usermgr = UserManager()
    objects = UserManager()

apps/login/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.db.models import Count

from .models import User,UserManager


# Create your views here.
def index(request):

    return render(request, 'login/index.html')

def register(request):
    if request.method == 'POST':
        post = request.POST

        data = {
            'f_name': post['f_name'],
            'l_name': post['l_name'],
            'email': post['email'],
            'passw': post['pass'],
            'cpass': post['cpass'],
	    'dob': post['dob'],
        }

        response = User.objects.register(**data)

        for i in response[1]:
            messages.error(request, i)

        for i in response[2]:
            messages.success(request, i)

    return redirect('/')

def login(request):
    if request.method == 'POST':
        data = {
            'email': request.POST['email'],
            'passw': request.POST['pass'],
        }

        response = User.objects.login(**data)

        if response[0]:
            messages.success(request, response[1])
            request.session['user_id'] = response[2].id
            request.session['user_name'] = response[2].first_name + ' ' + response[2].last_name
        else:
            messages.error(request, response[1])

    return redirect('main:index')

def logout(request):
    if 'user_id' in request.session:
        request.session.pop('user_id')
        request.session.pop('user_name')
        messages.success(request, "You have successfully logged out!")

    return redirect('/')

apps/login/templates/login/account.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>{{ title }}</title>
</head>
<div class="container">
    <div class="section">
        <div class="row">
            <a href="{% url 'books:index' %}" class="col s2">Home</a>
            <a href="{% url 'books:new_book' %}" class="col s4">Add Book and Review</a>
            <a href="{% url 'account:logout' %}" class="col s1">Logout</a>
        </div>
    </div>

    <div class="section">
        <div class="row">
            <h3>Name: {{account.first_name}} {{account.last_name}}</h3>
            <p>Email: {{account.email}}</p>
            <p>Total Reviews: {{count}}</p>
        </div>
    </div>

    <div class="section">
        <h5>You reviews</h5>
        <div class="row">
            {% for review in reviews %}
                <p><a href="{% url 'books:show_book' id=review.book.id %}">{{review.book.title}}</a></p>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

apps/login/templates/login/index.html
<!DOCTYPE html>
	<html>
	<head>
		<meta charset="utf-8">
		<meta name="description" content="Sign in page for User Dashboard">
	{% load staticfiles %}
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
	</head>
	<body>
		<div class="container">
			<h1>Welcome</h1>
			{% if messages %}
			<div>
				{% for message in messages %}
				{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
				<p>{{message}}</p>
				    </div>
				    <div>
                {% endif %}
            {% endfor %}

            {% for message in messages %}
			{% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}	
			<p>{{message}}</p>

                {% endif %}
            {% endfor %}
            </div>
			{% endif %}
			<div id="left">
			<h2>Register</h2>
	<form class="form-vertical" action="{% url 'login:register' %}" method="post">
			{% csrf_token %}
			<div class="form-group">
		<label class="col-sm-4-control-label">First Name: 
	<div class="col-sm-10">
		<input type="text" name="f_name" class="form-control"></label>
	</div>
		<div class="form-group">
		<label class="col-sm-4-control-label">Last Name: 
	<div class="col-sm-10">
		<input type="text" name="l_name" class="form-control"></label>
	</div>
	</div>
	<div class="form-group">
		<label class="col-sm-2-control-label">User Name: 
	<div class="col-sm-10">
		<input type="text" name="user_name" class="form-control"></label>
	</div>
	</div>
	<div class="form group">
		<label class="col-sm-2-control-label">Email: 
	<div class="col-sm-12">
		<input type="text" name="email" class="form-control"></label>
	</div>
	</div>
	<div class="form-group">
		<label class="col-sm-2-control-label">Password: 
	<div class="col-sm-10">
		<input type="password" name="pass"class="form-control"></label>
	</div>
	</div>
	<div class="form-group">
		<label class="col-sm-2-control-label">Confirm Password: 
	<div class="col-sm-10">
		<input type="password" name="cpass" class="form-control"></label>
	</div>
	</div>
	  <div class="form-group">
                <label class="col-sm-2-control-label">Date of Birth(format YYYY-MM-DD):
        <div class="col-sm-10">
                <input type="date" name="dob" class="form-control"></label>
        </div>
        </div>

		<input type="hidden" name="action" value="register">
		<button class="btn btn-default" id="submitbutton" type=" submit" name="submit" value="Register"></button>
	</form>
</div>	
	<div id="right">
        	<h2>Log In</h2>
        <form class="form-horizontal" action="{% url 'login:login' %}" method="post">
         {% csrf_token %}
	<div class="form-group">
		<label class="col-2-sm-control-label">Email: 
	<div class="col-sm-10">
		<input type="text" name="email"></label>
	</div>
	</div>
	<div class="form-group">
		<label class="col-2-sm-control-label">Password: 
	<div class="col-sm-10">
		<input type="password" name="pass"></label>
	</div>
	</div>
		<input type="hidden" name="action" value="login">
		<input class="btn btn-default" id="submitbutton" type="submit" name="submit" value="Login">
	</form>
	</div>
	</body>
</html>